# Generated by Django 2.2.5 on 2020-07-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200714_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='like',
            field=models.ManyToManyField(blank=True, to='posts.Images'),
        ),
    ]
