option = (("LP","Landscape Photography"),
("WP", "Wildlife Photography"),
("AP", "Aerial photography"),
("SAP", "Sports or Action Photography"),
("PP", "Portrait Photography"),
("ARP","Architectural Photography"),
("WEP", "Wedding or Event Photography"),
("FP", "Fashion Photography"),
("MP", "Macro Photography"),
("FBP", "Baby or Family Photography"),
("ABP","Abstract Photography"),
("BP", "Beauty Photography"),
("BWP","Black And White Photography"),
("FIP","Firework Photography"),
("FOP", "Food Photography"),
("MOP","Modeling Photography"),
("NP","Nature Photography"),
("NIP","Night Photography"),
("SP","Street Photography"),
("UWP","Underwater Photography"),
("VP","Vehicle Photography"),
("OT", "Others")
)