# Generated by Django 2.2.5 on 2020-07-14 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('img_type', models.CharField(choices=[('PP', 'Profile Picture'), ('UP', 'Post')], max_length=64)),
                ('catagory', models.CharField(blank=True, choices=[('LN', 'Landscape & Nature'), ('AM', 'Arial & Macro'), ('PO', 'Portrait'), ('AR', 'Architectural'), ('OT', 'Others')], max_length=16)),
                ('no_likes', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
